[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://project-starter-v12-e3354b551a67f9f409a.webflow.io"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
